### ISSUE TITLE
String encoding and decoding 

### ISSUE THREAD

**Issue by jasondeng1997** [kitex-contrib/codec-dubbo#11]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by YangruiEmma** [comment]
This issue is waiting to be assigned

**Comment by Lvnszn** [comment]
1

**Comment by jasondeng1997** [comment]
assign to [Lvnszn](https://github.com/Lvnszn)

**Comment by felix021** [comment]
The new plan is to implement fastcodec for Hessian2, more details: https://github.com/kitex-contrib/codec-dubbo/issues/28
