### ISSUE TITLE
How to Friendly Compatible with Collection Classes in Java

### ISSUE THREAD

**Issue by jasondeng1997** [kitex-contrib/codec-dubbo#12]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by YangruiEmma** [comment]
This issue is waiting to be assigned

**Comment by raspberry-hu** [comment]
assign to me

**Comment by felix021** [comment]
It'll be imlemented in https://github.com/kitex-contrib/codec-dubbo/issues/37
