### ISSUE TITLE
Ftr: use tool that can generate Go struct of its Java Class

### ISSUE THREAD

**Issue by jasondeng1997** [kitex-contrib/codec-dubbo#14]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by YangruiEmma** [comment]
This issue is waiting to be assigned

**Comment by jasondeng1997** [comment]
assign to me

**Comment by felix021** [comment]
The new plan is to generate IDL from java source, more details: https://github.com/kitex-contrib/codec-dubbo/issues/37
