### ISSUE TITLE
add encode and test for double, boolean, int, long and null 

### ISSUE THREAD

**Issue by jasondeng1997** [kitex-contrib/codec-dubbo#20]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bookjiang** [comment]
pls assign to me

**Comment by jasondeng1997** [comment]
assign to [bookjiang](https://github.com/bookjiang)

**Comment by VaderKai** [comment]
pls assign to me

**Comment by jasondeng1997** [comment]
assign to [VaderKai](https://github.com/VaderKai)

**Comment by felix021** [comment]
The new plan is to implement fastcodec for Hessian2, more details: https://github.com/kitex-contrib/codec-dubbo/issues/28
