### ISSUE TITLE
add decode  and test for double, boolean, int, long and null 

### ISSUE THREAD

**Issue by jasondeng1997** [kitex-contrib/codec-dubbo#3]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ChangedenCZD** [comment]
🆗

**Comment by jasondeng1997** [comment]
assign to [ChangedenCZD](https://github.com/ChangedenCZD) c

**Comment by VaderKai** [comment]
pls assign to me

**Comment by jasondeng1997** [comment]
#18

**Comment by felix021** [comment]
The new plan is to implement fastcodec for Hessian2, more details: https://github.com/kitex-contrib/codec-dubbo/issues/28
