### ISSUE TITLE
[P1] Proposal: Service registry and discovery on zookeeper

### ISSUE THREAD

**Issue by felix021** [kitex-contrib/codec-dubbo#35]
Although Kitex already has a module for zookeeper [registry-zookeeper](https://github.com/kitex-contrib/registry-zookeeper), it's not compatible with the dubbo way.

In this proposal, we suggest the implementation of a dubbo compatible module. Maybe only a small pull request is needed to the [registry-zookeeper](https://github.com/kitex-contrib/registry-zookeeper).

The detailed plan is left for anyone who claims this task.

**Comment by DMwangnima** [comment]
Interface-Level service discovery has been supported. Please refer to #63 .

**Comment by felix021** [comment]
Service registry implemented in https://github.com/kitex-contrib/codec-dubbo/pull/67
