### ISSUE TITLE
Feature add gomodule

### ISSUE THREAD

**Issue by jasondeng1997** [kitex-contrib/codec-dubbo#4]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HeyJavaBean** [comment]
This issue is waiting to be assigned

**Comment by jasondeng1997** [comment]
I FIX IT
https://github.com/kitex-contrib/codec-hessian2/pull/17
