### ISSUE TITLE
fix DubboHeader 

### ISSUE THREAD

**Issue by jasondeng1997** [kitex-contrib/codec-dubbo#5]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by iSuperCoder** [comment]
pls assign to me

**Comment by jasondeng1997** [comment]
pls assign to [iSuperCoder](https://github.com/iSuperCoder)

**Comment by felix021** [comment]
It's already implemented
