### ISSUE TITLE
Support to decode list

### ISSUE THREAD

**Issue by jasondeng1997** [kitex-contrib/codec-dubbo#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Charlie17Li** [comment]
pls assign it to me :)

**Comment by felix021** [comment]
The new plan is to implement a fastcodec for Hessian2, more details: https://github.com/kitex-contrib/codec-dubbo/issues/28
