### ISSUE TITLE
[P1] Proposal: better unwrapping of java exception

### ISSUE THREAD

**Issue by felix021** [kitex-contrib/codec-dubbo#66]
DubboCodec should already be able to decode the exception thrown by dubbo-java, but currently the called may not be able to retrieve it since we it's dumped into a string and returned:

```
return fmt.Errorf("dubbo side exception: %v", exception)
```

A better approach is to return a special kind of error which wraps the Exception type.

```
type DubboError struct {
    exception interface{}
}

func (e *DubboError) Error() string {
    ...
}

func (e *DubboError) Exception() interface{} {
    return e.exception
}

```

**Comment by DMwangnima** [comment]
Done by #74.
