### ISSUE TITLE
[P1] Support java.math.BigDecimal and java.math.BigInteger

### ISSUE THREAD

**Issue by DMwangnima** [kitex-contrib/codec-dubbo#76]
java.Object, java.Time and some basic java types are implemented by idl-ref way. These types are maintained in /java directory. These PRs are related implementations:
- https://github.com/kitex-contrib/codec-dubbo/pull/62
- https://github.com/cloudwego/kitex/pull/1167

For now, we need to support java.math.BigDecimal and java.math.BigInteger. **dubbo-go-hessian2** has supported encode/decode BigDecimal and BigInteger but it makes use of "github.com/dubbogo/gost/math/big".Decimal and Integer directly:
<img width="623" alt="image" src="https://github.com/kitex-contrib/codec-dubbo/assets/33331974/895f596a-d4a3-44d1-a710-01758eaecfb0">
For supporting users with unified using experiences, we need to extend these two types in /java directory.

**Comment by felix021** [comment]
Btw, please help fix the problem of overwriting idl-ref.yml each time kitex is executed.

**Comment by DMwangnima** [comment]
Overwriting idl-ref.yml has been resolved by https://github.com/cloudwego/kitex/pull/1227

**Comment by DMwangnima** [comment]
This has been solved by idl-ref functionality. Waiting for doc updating.
