### ISSUE TITLE
P2: do not perform replacement on handler.go if -service is not specified

### ISSUE THREAD

**Issue by felix021** [kitex-contrib/codec-dubbo#77]
The `-service` option is not specified by Kitex is still trying to perform the replacement:

> kitex -module test6 -protocol Hessian2 -hessian2 java_extension api.thrift
> Adding apache/thrift@v0.13.0 to go.mod for generated code .......... Done
> replace java object fail, you can fix it then regenerate open 
> /xxx/dubbo/test6/handler.go: no such file or directory

**Comment by DMwangnima** [comment]
Kitex cmd tools does not consider the situation without -service flag.

**Comment by DMwangnima** [comment]
BTW, I think our [codec-dubbo-tests](https://github.com/kitex-contrib/codec-dubbo-tests) should generate code automatically in CI so that problems in this part would be exposed.

**Comment by felix021** [comment]
fixed in https://github.com/cloudwego/kitex/pull/1234
