### ISSUE TITLE
ReflectResponse needs to support reflecting fields end with "_"

### ISSUE THREAD

**Issue by DMwangnima** [kitex-contrib/codec-dubbo#82]
To avoid naming conflicts, thriftgo would add underscore for the fields that start with "New" and end with "Result", "Args".(Refer to https://www.cloudwego.io/zh/docs/kitex/faq/).

ReflectResponse needs to check this feature and make two fields that are only distinguished by an underscore map successfully.

**Comment by DMwangnima** [comment]
After testing, I found that we could not solve this problem in ```ReflectResponse```.
As for Kitex -> Dubbo,
If request struct contains NewXXX field, Dubbo side could not parse this field.
If response struct contains NewXXX field, dubbo-go-hessian2 could not parse this field.

If we do not modify the generated contents(add a flag in thriftgo to control whether adding underscore or not / reg operation in kitex cmd tool), we should fork dubbo-go-hessian2 and modify the field mapping.
cc @felix021

**Comment by felix021** [comment]
Could be solved by running kitex tool with `-thrift compatible_names=false`
